# General Jekyll Config
highlighter: rouge
url: http://vaughanhilts.me
lsi: false
description: "Just a place to store my random thoughts and contributions to the world."
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor/]
