# General Jekyll Config
highlighter: none
url: http://vaughanhilts.me
lsi: false
description: "Blogging about technology, software, .NET and other cool things"
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
